[workspace]
members = [
    "first-party/controls",
    "first-party/interp-map",
    "first-party/copcomp/rust",
    "rio-benches",
    "c2018",
    "c2018/ctre-elevator-tuning",
    "c2018/path-gen",
    "c2018/coord-frames",
]

[profile.dev]
# We counterintuitively don't need this, since we can't view debug info ATM
debug = false

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"
