[workspace]
members = [
    "ert",
    "c2019",
    "rio-benches",
]

[profile.dev]
# We counterintuitively don't need this, since we can't view debug info ATM
debug = false

[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"
