[package]
name = "ert"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aos_sync = { path = "../third-party/aos-sync" }
nix = "0.15.0"
lock_api = "0.3.1"
libc = "0.2.66"
