version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:1.31
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "Cargo.lock" }}
      - run: cargo build
      - save_cache:
          key: v1-{{ checksum "Cargo.lock" }}
          paths:
            - target
