[package]
name = "copcomp"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]
edition = "2018"

[lib]
name = "copcomp"
path = "src/lib.rs"

[[bin]]
name = "copcomp-2019-test"
path = "src/2019-test.rs"

[dependencies]
serde = "1.0.84"
serde_cbor = "0.9.0"
serde_derive = "1.0.84"
