[package]
name = "copcomp"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.84"
serde_cbor = "0.9.0"

[dev-dependencies]
serde_derive = "1.0.84"
